extends: airbnb-base
env:
    node: true
    es6: true
rules:
    no-console:
      - warn
    no-unused-vars:
      - warn
    import/no-unresolved:
      - off
    import/no-extraneous-dependencies:
      - off
    quotes:
      - error
      - single
      - "avoid-escape"
